# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: SAST 
  jobs:
  - job: SAST
    displayName: 'SAST'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script 1 '
- stage: SCA 
  jobs:
  - job: SCA
    displayName: 'SCA'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script 2 '

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
- stage: Container_Security 
  jobs:
  - job: Container_Security
    displayName: 'Container Security'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script 3 '

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
